#!/bin/bash
echo "Creating virtual environment"
if [ ! -d venv ]; then
    python3 -m venv venv
fi
echo "Activating virtual environment"
. venv/bin/activate 

echo "Checking packages..."
installed_packages=`pip3 freeze`
expexted_packages=`cat requirements.txt`
if [ "$installed_packages" != "$expexted_packages" ]; then  
    echo "Installing packages..."
    pip3 install -r requirements.txt
fi

if [ ! -f run-dev ]; then
    read -p "TELEGRAMBOT_TOKEN: " TELEBOT_TOKEN
    read -p "PROXI_HOST: " PROXI_HOST
    printf "#!/bin/bash\n. venv/bin/activate\nPROXI_HOST=\"$PROXI_HOST\" TELEBOT_TOKEN=\"$TELEBOT_TOKEN\" python3 wsgi.py" > run-dev
fi

PURPLE='\033[0;35m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "\n\nDevelopment build is ${GREEN}ready to use${NC}\n\n"
printf "${PURPLE}source run-dev${NC}\n\n"