#!/bin/bash

YELLOW='\033[0;33m'
PURPLE='\033[0;35m'
GREEN='\033[0;32m'
NC='\033[0m'

printf "${YELLOW}Deactivating virtual environment${NC}\n"
deactivate 

printf "${RED}Deleting virtual environment${NC}\n"
rm venv -r
echo "Creating virtual environment"
python3 -m venv venv

echo "Activating virtual environment"
. venv/bin/activate 

installed_packages=`pip3 freeze`
expexted_packages=`cat requirements.txt` 
echo "Installing packages..."
pip3 install -r requirements.txt


read -p "PROXI_HOST: " PROXI_HOST 
read -p "TELEGRAMBOT_TOKEN: " TELEBOT_TOKEN 


printf "\
#!/bin/bash\n\
PROXI_HOST=$PROXI_HOST\n\
TELEBOT_TOKEN=$TELEBOT_TOKEN\
" > config


printf "\n\nDevelopment re-build was ${GREEN}succesful${NC}\n\n"
printf "${PURPLE}source run-dev${NC}\n\n"