#!/bin/bash
YELLOW='\033[0;33m'
NC='\033[0m'
. venv/bin/activate
. config
cd app 
printf "${YELLOW}Starting development server...${NC}\n" 
PROXI_HOST=$PROXI_HOST TELEBOT_TOKEN=$TELEBOT_TOKEN python3 wsgi.py  
cd ..  
